# src/agents/state.py
import operator
from typing import TypedDict, List, Dict, Any, Annotated
from typing_extensions import Required

class GraphState(TypedDict, total=False):
    # Core User Inputs
    ticker: Required[str]
    
    # --- Step 2: Graph Routing Discoveries ---
    macro_path: List[str]                   # Discovered sequence of nodes from NetworkX
    structural_weights: List[Dict[str, Any]] # Edge metadata: [{"source": "Steel", "weight": -0.8, "node_type": "COMMODITY"}]
    
    # --- Step 3: Ingestion & Multi-Vector Scraping ---
    generated_search_queries: Dict[str, Any] # Target strings generated by Query Planner (Gemini Flash)
    scraped_market_data: Dict[str, List[Dict[str, Any]]] # Live data from RSS/calendars grouped by node name
    
    # --- Corporate Metrics Layer ---
    current_price: float
    market_metrics: Dict[str, Any]          # Corporate fundamentals (P/E, Debt-to-Equity, Margins, etc.)
    
    # --- Step 4: Agent Worker Critiques ---
    fundamental_critique: str               # Output from Fundamental Agent
    sentiment_critique: str                 # Output from Sentiment Agent
    
    # --- Step 5: Final Synthesis Engine Outputs ---
    direction: str                          # BULLISH / BEARISH / NEUTRAL
    confidence_score: float                 # Pipeline confidence score (0.0 to 1.0)
    synthesis_rationale: str                # Consolidated Investment thesis rationale
    
    # --- Governance & Monitoring Telemetry ---
    token_count: int                        # Running total of processed LLM tokens via TokenGovernor
    execution_logs: Annotated[List[str], operator.add] # Thread-safe log accumulator